spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${POLARECO_RDS_ENDPOINT}/test?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${POLARECO_RDS_USERNAME}
    password: ${POLARECO_RDS_PASSWORD}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
cloud:
  aws:
    credentials:
      accessKey: ${AWS_IAM_AccessKey}
      secretKey: ${AWS_IAM_SecretKey}
    s3:
      bucket: polareco-bucket
      dir: post_Image
    region:
      static: ap-northeast-2
    stack:
      auto: false